### ISSUE TITLE
Add image to breadcrumb

### ISSUE THREAD

**Issue by jhunflx** [poteto/ember-crumbly#77] opened 2016-05-14 05:44 UTC
Hello!

Is it possible to add an image to one or more breadcrumb items such that the html looks something like this?

`<li class="breadcrumb-item">
    <a id="ember404" class="ember-view" href="/foo"><img src="/assets/images/cow.png" /> Cow</a>
  </li>`

or

`<li class="breadcrumb-item">
    <a id="ember404" class="ember-view" href="/foo"><i class="fa fa-cow"></i> Cow</a>
  </li>`

Many thanks!

Julie

**Comment by abhilashlr** [comment] 2016-05-14 10:54
One can create a custom template in the same name as the add-on - Bread-crumbs.hbs

**Comment by jhunflx** [comment] 2016-05-18 18:47
Where does this template reside?  In the same directory as my route?  Currently I have something like this:

```
controller.coffee
route.coffee
template.hbs
bread-crumbs.hbs
```
where `template.hbs` looks like this:
```
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-md-10">
    <h2>{{bread-crumbs tagName="ol" outputStyle="bootstrap" linkable=false}}</h2>
  </div>
</div>
{{outlet}}
```

and `bread-crumbs.hbs` looks like this:

```
{{log breadCrumb}}
{{#bread-crumbs outputStyle="bootstrap" linkable=true as |component breadCrumb|}}
  {{#bread-crumb route=breadCrumb breadCrumbs=component}}
    <img src="/assets/images/cow.png" /> {{breadCrumb.title}}
  {{/bread-crumb}}
{{/bread-crumbs}}
```

but the code never hits `{{log breadCrumb}}` leading me to believe it's not getting called.  Do you have any sample code of what this should look like?

Thanks!

**Comment by abhilashlr** [comment] 2016-05-29 06:31
Did it already work for you?

If not, can you try adding the bread-crumbs.hbs inside **app/components/templates/** path?

**Comment by jhunflx** [comment] 2016-06-05 20:24
Unfortunately not.  I tried putting the file in **app/components/templates** as well as in my **app/pods/components/templates**.

Do you have an example of this working in your project that you can share?

**Comment by abhilashlr** [comment] 2016-06-06 09:27
It should be in either

app/components/bread-crumbs/template.hbs
Or
app/templates/components/bread-crumbs.hbs

**Comment by jhunflx** [comment] 2016-06-07 00:55
The correct path is `app/components/bread-crumbs/template.hbs`

Thank you for taking the time to point me in the right direction!

**Comment by abhilashlr** [comment] 2016-06-07 00:57
Cool 😎

**Comment by fsmanuel** [comment] 2016-10-17 20:01
I'm closing this as the problem is solved.

**Closed by fsmanuel** 2016-10-17 20:01 UTC
