### ISSUE TITLE
Make active breadcrumb not be an anchor tag

### ISSUE THREAD

**Issue by barryofguilder** [poteto/ember-crumbly#61] opened 2016-02-02 22:01 UTC
It would be great if there was an option to make the active breadcrumb not be an anchor tag. I'm using the breadcrumb with Bootstrap and their [examples](http://getbootstrap.com/components/#breadcrumbs) show the active breadcrumb to just have text within the list item (no anchor tag).

```html
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Library</a></li>
  <li class="active">Data</li>
</ol>
```
Currently, I'm adding my own custom styles to make the active breadcrumb look like normal text instead of a link, but I'm still able to click on it, which just goes to the same page I'm on.

**Comment by fsmanuel** [comment] 2016-10-17 20:05
@barryofguilder is this still an active issue?

**Comment by barryofguilder** [comment] 2016-10-17 20:22
@fsmanuel, I'm not sure. I haven't worked on the project that was making use of breadcrumbs in months. I can check on this sometime this week though.

**Comment by dguettler** [comment] 2016-10-18 03:13
Can't reproduce this issue, closing for now.

**Closed by dguettler** 2016-10-18 03:13 UTC

**Comment by dguettler** [comment] 2016-10-18 03:18
One side note, if you manually define `linkable` in your route it takes precedence over the calculated one.
https://github.com/poteto/ember-crumbly/blob/master/addon/components/bread-crumbs.js#L103
