### ISSUE TITLE
Crumb now working is same route

### ISSUE THREAD

**Issue by samdemaeyer** [poteto/ember-crumbly#36] opened 2015-08-14 11:46 UTC
When transitioning to the same route with another id, the crumb is not being updated.
However, when reload, the breadCrumb will be updated.
Please find the video **[here](http://quick.as/0rJbirbYk)** to illustrate the problem.

**Comment by cibernox** [comment] 2015-08-14 12:45
Just to give exact context, the problem is in this lines:  https://github.com/poteto/ember-crumbly/blob/develop/addon/components/bread-crumbs.js#L33-L49

That computed property gets updated whenever the user transitions to a route with a different name, but in our case we're transitioning to the same route with a different id.

I don't know if there any public API in the router or the application controller that exposes more information about the value of the dynamic segment of the active route, so that CP can add that as a dependent key.

**Comment by gmurphey** [comment] 2015-08-14 16:09
This is fixed in #27.

**Comment by cibernox** [comment] 2015-08-14 16:31
@gmurphey Good to know. Do you know if that if going to be blocked much longer?

**Comment by gmurphey** [comment] 2015-08-14 16:37
@cibernox It's currently blocked by #30, which is fixed by #31 and just need to be merged.

**Comment by gmurphey** [comment] 2015-08-14 16:41
@cibernox #27 does work on its own if you want to use that branch for now. It's just that the tests are failing due to an unrelated issue outlined in #30.

**Comment by cibernox** [comment] 2015-08-14 16:52
I asked because #31 seems to be there for around a month, so perhaps was not merged for some problem I wasn't aware.

**Comment by poteto** [comment] 2015-08-15 01:16
Super sorry about that guys! I accidentally unwatched the repo so I wasn't getting any notifications.

**Comment by gmurphey** [comment] 2015-08-15 01:24
No problem, @poteto! Rebasing #27 now!

**Comment by samdemaeyer** [comment] 2015-08-17 09:24
@poteto, @gmurphey 
Hi Guys, thanks for the quick release! 
There is however an issue, if you use the component like this: 
```hbs
{{#bread-crumbs tagName="ol" outputStyle="bootstrap" linkable=true as |component crumb|}}
  {{#if (eq crumb.title 'Authenticated')}}
    <i class="ti-home"></i>
  {{else}}
    {{crumb.title}}
  {{/if}}
{{/bread-crumbs}}
```
The output does not generate the `<li>` & `<a>` tags any more.
I just updated to the new release. This is how it rendered in 0.2.0:
<img width="197" alt="screen shot 2015-08-17 at 10 18 32" src="https://cloud.githubusercontent.com/assets/7160913/9301842/7664ed10-44c9-11e5-8261-a471f34aaadf.png">


This is what is being rendered in the new release: 
![screen shot 2015-08-17 at 10 14 44](https://cloud.githubusercontent.com/assets/7160913/9301839/70c24cf4-44c9-11e5-8d74-54367984a8b6.png)

```html
<ol>            
  <i class="ti-home"></i>
  Calendar
  Personal
</ol>
```

**Comment by gmurphey** [comment] 2015-08-18 00:00
Hi, @samdemaeyer! As part of the fix for #30, a `bread-crumb` component was added to render each individual crumb. I believe your template should become:

``` javascript
{{#bread-crumbs tagName="ol" outputStyle="bootstrap" linkable=true as |component crumb|}}
  {{bread-crumb route=crumb breadCrumbs=component}}
    {{#if (eq crumb.title 'Authenticated')}}
      <i class="ti-home"></i>
    {{else}}
      {{crumb.title}}
    {{/if}}
  {{/bread-crumb}}
{{/bread-crumbs}}
```

Let me know if that doesn't work for you. I'm happy to revisit it.

**Comment by samdemaeyer** [comment] 2015-08-18 07:45
@gmurphey, Thanks, that makes sense. It works fine! @poteto, could you document this change in the README. Again, thanks for the quick response and the help!

**Comment by gmurphey** [comment] 2015-08-18 17:08
@samdemaeyer @poteto just updated the documentation in #39.

**Comment by fsmanuel** [comment] 2016-10-17 20:15
@gmurphey can we close the issue?

**Comment by fsmanuel** [comment] 2016-10-17 20:16
@samdemaeyer can we close the issue?

**Comment by gmurphey** [comment] 2016-10-17 20:16
@gmurphey Seems okay to close to me. #39 has been merged.

**Comment by gmurphey** [comment] 2016-10-17 20:16
@fsmanuel Seems okay to close to me. #39 has been merged.

**Closed** 2016-10-17 20:24 UTC
